### ISSUE TITLE
Moss idx doesn't handle packages having different relnums

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/moss#16]
Consider a local collection with the following files in it:
```
bzip2-1.0.8-1-1-x86_64.stone
bzip2-1.0.8-2-1-x86_64.stone
```
This is obviously a valid scenario and the both packages should be indexed (with `-2` being chosen for most installation cases).

Unfortunately this kills the poor `moss idx` command.
```
@[../source/moss/client/cli/index.d:117]  FATAL     Trying to include two packages with same release number: bzip2-devel-1.0.8-1.x86_64 - bzip2-devel-1.0.8-2.x86_64
object.Error@(0): A fatal log message was logged
(non-helpful backtrace)
```

**Comment by ikeycode** [comment]
What, I never ment to close it.

**Comment by ReillyBrogan** [comment]
Yeah I haven't noticed it since.
