### ISSUE TITLE
Can't install a local .stone file: stuck at downloading

### ISSUE THREAD

**Issue by livingsilver94** [serpent-os/moss#24]
## Issue

moss gets stuck at installing a local .stone file. With "local" I mean a .stone provided via a path, not a package in a local, registered repository.

```
❯ moss -D ~/Development/SerpentOS/sosroot it ../elfutils/libelf-0.148-1-1-x86_64.stone                                
The following packages will be installed

libelf - 0.148-1  

Do you want to continue? [ Yes / No ] y
 
 ◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼  100% libelf-0.148-1-1-x86_64.stone



 
 Total downloaded
 ◼◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻◻    0% 
 
 Cache activity
```

Clearly, there's no file to download since it's local. When a local package to install has dependencies, deps are downloaded but then the target package "download" sits just like in the example above.

## How to reproduce

Build with boulder any stone you want. Then launch the command above.

**Comment by ermo** [comment]
Was fixed at some point. Works now.
