### ISSUE TITLE
boulder: Do not use `/.moss` store

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/moss#271]
When invoking `boulder build` as root it uses `/.moss` for the store, rather than a *private* moss store.
This seems bad.

**Comment by ermo** [comment]
I think it's _supposed_ to use `/var/cache/boulder/.moss`, but I don't think we ever got the requisite defaults locked down.

**Comment by ikeycode** [comment]
OK. So for recipes should we set a custom moss root in the justfile?

**Comment by tarkah** [comment]
Let's just have a shared moss root in the boulder cache directory?

**Comment by ikeycode** [comment]
Or even that yeah. Then if you do use as a shared system user or root it's still a disk share.

Main thing we want is to be able to safely nuke it without borking the host.

Making it default behaviour would mean not being locked to the `justfile` workflow too!
