### ISSUE TITLE
boulder: Enable simultaneous, isolated builds

### ISSUE THREAD

**Issue by ermo** [serpent-os/moss#272]
The current implementation of how boulder decides which dirs to use lives [here](https://github.com/serpent-os/moss/tree/main/boulder/src//env.rs)

**Discussion**

> **Reilly Brogan**
> For the boulder moss dir I think we should use xdg if rootless, and default to /var/cache/boulder if rootful
> **ermo**
> There's an argument to be made that, like Fabio suggests, boulder should never be rootful:  What if two boulder instances are running simultaneously as root? Won't they clobber `/var/cache/boulder/.moss/` if so? Ungood.
> **Reilly Brogan**
> I do want to run multiple boulder instances at once 
> **ermo**
> I think the real solution here is to have a tmp-file-like `<prefix>/.moss-<unique id>` per build invocation of boulder.
> That'll then work regardless of whether we're rootful or not.
> And then the chroot thing needs to ask the user "which id did you want to chroot into?" interactively if the id is not specified.
> which implies that boulder needs to output this ID when running with `--verbose` or as part of a build failure report.
> tarkah / Ikey Doherty: ^ thoughts?
> I think it'll be nice UX wise.
> The ID is probably unique enough if you take the boulder PID + UTC time-of-day + name of the recipe?
> **tarkah**
> `.moss/` is used for caching package downloads
> we don't want to redownload every time
> **ermo**
> how might we solve this?
> i.e. maintain the benefits of some sharing, yet have unique roots otherwise?
> is, say, some sort of bind-mounting possible...?
> or even desirable?
> **tarkah**
> we support custom cache dir
> so we can use unique `.moss-<id>/` with a shared cache dir
> `/var/cache/boulder/.moss-cache` and then `/tmp/.moss-<id>` or something
> **ermo**
> what happens in terms of simultaneous builds on the same machine that both want to write the same cache item?
> as in: Do we need a sort of semaphore or queue here?
> tarkah
> lockfile?
> **ermo**
> think of the case where one builder can be partitioned into cgroups of 4/8/16/32/(...) cores/threads per build type (small/normal/yuge)
> meaning an org could have a big arse heavy metal builder and then partition build cgroups on the fly (or via some other means of partitioning)
> but on shared storage re. cache
> etc.

Related to #271

**Comment by tarkah** [comment]
I think we can safely close this with:

#273 and #278

**Comment by ikeycode** [comment]
Yay!

**Comment by ermo** [comment]
This appears to work as long as you do not attempt to make two concurrent builds of the same recipe.
