### ISSUE TITLE
moss: Trigger integration

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/moss#40]
High level requirements

 - Triggers run in isolated environment *before* activating the transaction, allowing safe failures
 - Triggers defined using simple YAML configuration files
 - Easy capture globs for path matching (in tree as `crates/fnmatch`)

Technical details:

 - Due to our use of `tokio`, clone based containers are a little bit more difficult.
 - Load all system triggers from "target `/etc`" and "target `/usr" asynchronously
 - Match all installed paths (from `vfs::Tree`) against `fnmatch` globs to detect matches
 - Use our `container` crate to execute each trigger *in isolation*
 
 Caveats:

 Certain system actions can only be sanely (not necessarily *safely*) performed post-activation, including:

 - Reloading udev
 - Reexec of systemd

Thus our triggers will be split into `postblit` and `postactivate`, with the expectation of `postblit` triggers being container-isolated, and `postactivate` being actions that would normally happen with a reboot anyway.

**Comment by ermo** [comment]
@ikeycode What's the status here? Close to being "done"?
