### ISSUE TITLE
boulder chroot design proposal notes

### ISSUE THREAD

**Issue by ermo** [serpent-os/moss#93]
The goal of this issue is to describe a method with which to be able to enter clean chroots at various points.

## captured notes

**tarkah**
So for our boulder roots, since we don't populate a moss root inside it, we can't incrementally add addtl. packages, it always needs to be a full blit. This only comes up from what I can tell when we build then chroot after. In boulder-d, chrooting installs a couple more packages (vi, nano, etc). In our case, we'd need to install these during build otherwise we'd have to reblit the rootfs during chroot and that'd delete the root which defeats the purpose.

> **Ikey Doherty:** thoughts?
>

**ermo**
FTR, one of the things I have suggested is that we ensure that it is possible to chroot into a builddir before/after a certain build phase so as to be able to do build/environment troubleshooting session and possibly even being able to do a patch from within a cleanly created builddir (and smuggling it out aftwards, so it can be properly added to the recipe).
so it may pay to have a fixed list of "essential troubleshooting+patch-authoring tools"...?
(this might need to be editable per user, so the user can add/remove stuff per their preferences/workflow)
**tarkah**
That makes sense and should be super easy to enable
**ermo**
the reason for this, is that it allows e.g. the kernel maintainer to update to a new version, then do a `boulder chroot --after-phase=setup`
then the kernel maintainer can do the `make menuconfig` dance, verify that it's sane, smuggle out the new config, then exit the chroot and run the normal boulder build routine.
using the actual-as-unpacked source, not a (hopefully accurate) separate tree.
(this was the preferred way of doing patches in Conary-based Foresight Linux development)
it also means that it becomes possible to iteratively develop and apply patches and then inspect them in the chroot.
**tarkah:** The idea here is that you can enter either at the _start_ (before running any phase instructions) or at the _end_ (after running all listed phase instructions) of each build phase
so you can technically set up a recipe, then ask it to only download and unpack the sources by running `boulder chroot --before-phase=setup` to get a fully clean and reproducible chroot in which you can develop the necessary build instructions.
ideally, you would be able to access all macros (actions, definitions) from within this chroot
with, say, `$a_` (`%action`) and `$d_` (`%(definition)`) prefixes...?
so to run e.g. `%reconfigure` in a clean root, you'd do a `boulder chroot --before-phase=setup` and then inside the chroot, you would run `$a_reconfigure`
the suggested `$a_(...)` and `$d_(...)` stuff is meant to simulate namespaces.
**Ikey Doherty:** Thoughts?
I suppose I could write up a design issue.

**Comment by ermo** [comment]
It might be smart if we (at some point) enable support for capturing the line number of the original site in the recipe (before any meaningful parsing/expansion has happened) at which the currently active breakpoint (`%break_continue` or `%break_exit`) was invoked?

**Comment by tarkah** [comment]
@ermo thanks for detailing the above :+1: 

As it relates to the original issue problem statement, do we still have a need for a CLI flag based `--after-phase=setup` approach since the breakpoints cover this with much more flexibility? Let's just support a single path for inspecting chroot during a build, which is via breakpoints.

**Comment by ermo** [comment]
The thing about having the ability to do things from the cmd line is that you know you are testing the recipe as-is.

As soon as you edit the recipe, it's technically a change.

**Comment by ikeycode** [comment]
implemented
